# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

project 'FreeAgent Tech Test.xcodeproj'

use_frameworks!

target 'FreeAgent Tech Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'

  target 'FreeAgent Tech TestTests' do
    inherit! :search_paths
    
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

  target 'FreeAgent Tech TestUITests' do
    # Pods for testing
  end

end
